from typing import Protocol, List, Tuple
from langchain_core.documents import Document

class SemanticCacheProtocol(Protocol):
    def similarity_search_with_score(self, query: str, k: int = 1) -> List[Tuple[Document, float]]: ...
    def add_texts(self, texts: List[str], metadatas: List[dict]) -> None: ...
    def clear(self) -> bool: ...
